print(" ini python pemrograman")
print(" tambahan program ")
print(" dari vbc ")
print(" dari repository github")
print(" coba dari repository lagi")
print(" tes lagi dari repo ")
print(" mencoba membuat program python ")